name: healthy_meter
description: A Health Meter for everybody.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_flip_counter: ^0.2.4
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  http: ^0.13.4
  signalr_core: ^1.1.1
  charts_flutter: ^0.12.0
  fl_chart: ^0.55.0
  intl: ^0.17.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Black.ttf
        - asset: assets/fonts/Vazir-Bold.ttf
        - asset: assets/fonts/Vazir-Light.ttf
        - asset: assets/fonts/Vazir-Medium.ttf
        - asset: assets/fonts/Vazir-Regular.ttf
        - asset: assets/fonts/Vazir-Thin.ttf
        - asset: assets/fonts/Vazir-Variable.ttf
